version: "3.8"

services:
  vpn:
    build: .
    container_name: vpn-gateway-unifor
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
      - /dev/ppp:/dev/ppp
    sysctls:
      - net.ipv4.ip_forward=1
    environment:
      - VPNADDR=${VPN_ADDR}
      - VPNUSER=${VPN_USER}
      - VPNPASS=${VPN_PASS}
      # - TRUSTED_CERT=your_sha256_hash_here
    networks:
      vpn-unifor-internal:
        ipv4_address: 172.28.0.2
    restart: unless-stopped

networks:
  vpn-unifor-internal:
    name: vpn-unifor-internal
    external: true
